name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
      placeholder: What feature would you like?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem It Solves
      description: What problem does this feature address?
      placeholder: What pain point does this solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal implementation
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Are there alternative solutions you've thought about?
      placeholder: What other approaches could work?

  - type: dropdown
    id: labels
    attributes:
      label: Additional Labels
      description: Select any that apply (optional)
      multiple: true
      options:
        - desktop
        - android
        - UI
        - documentation
        - refactor
        - improvement
        - code tools

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any mockups, examples, or additional information
      placeholder: Add any other context, mockups, or examples here
