name: CSS Selectors

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    css-selectors:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Setup node.js
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: "pnpm"

            - name: Set PNPM store path
              run: pnpm config set store-dir ~/.pnpm-store

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Cache PNPM dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            - name: Install Playwright Browsers
              run: pnpm playwright install --with-deps chromium

            - name: Run Playwright tests
              run: pnpm test
